In [2]:
import numpy as np
import pandas as pd

In [3]:
np.random.seed(77)
someData = np.random.randint(0, 101, (4, 3))
print(someData)
someIndex = ["A", "B", "C", "D"]
someColumn = ["First", "Second", "Third"]

[[87 95 84]
 [84 37 24]
 [31 96 57]
 [39 44 19]]


In [4]:
someDataFrame = pd.DataFrame(data=someData, index=someIndex, columns=someColumn)

In [5]:
someDataFrame

First  Second  Third
A     87      95     84
B     84      37     24
C     31      96     57
D     39      44     19

Reading CSV file

In [6]:
pwd

'/Users/fengyingcong/Desktop/DataScience_Practice/pandas'

In [31]:
tipsDataFrame = pd.read_csv("./tips.csv")

In [8]:
tipsDataFrame

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name         CC Number Payment ID  
0    Christy Cunningham  3560325168603410    Sun2959  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
4          Tonya Carter  4832732618637221    Sun2251  
..                  ...               ...        ...  
239       Michael Avila  5296068606052842    Sat2657  
240      Monica Sanders  3506806155565404    Sat1766  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  
243     Michelle Hardin  3511451626698139    Thur672  

[244 rows x 11 columns]

In [9]:
tipsDataFrame.iloc[0]

total_bill                       16.99
tip                               1.01
sex                             Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                  8.49
Payer Name          Christy Cunningham
CC Number             3560325168603410
Payment ID                     Sun2959
Name: 0, dtype: object

In [10]:
tipsDataFrame

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name         CC Number Payment ID  
0    Christy Cunningham  3560325168603410    Sun2959  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
4          Tonya Carter  4832732618637221    Sun2251  
..                  ...               ...        ...  
239       Michael Avila  5296068606052842    Sat2657  
240      Monica Sanders  3506806155565404    Sat1766  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  
243     Michelle Hardin  3511451626698139    Thur672  

[244 rows x 11 columns]

In [37]:
tipsDataFrame.iloc[0:3, 0:3]

total_bill   tip     sex
0       16.99  1.01  Female
1       10.34  1.66    Male
2       21.01  3.50    Male

In [12]:
tipsDataFrame['total_bill']

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...  
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [13]:
tipsDataFrame.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

In [14]:
total_bill = tipsDataFrame['total_bill']

In [15]:
total_bill

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...  
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [16]:
print(total_bill[2])

21.01


Selecting multiple column

In [17]:
tipsDataFrame[['Payer Name', 'price_per_person']]

Payer Name  price_per_person
0    Christy Cunningham              8.49
1        Douglas Tucker              3.45
2        Travis Walters              7.00
3      Nathaniel Harris             11.84
4          Tonya Carter              6.15
..                  ...               ...
239       Michael Avila              9.68
240      Monica Sanders             13.59
241          Keith Wong             11.34
242        Dennis Dixon              8.91
243     Michelle Hardin              9.39

[244 rows x 2 columns]

Creating a new column

In [18]:
tipsDataFrame['tips_percentage'] = 100 * tipsDataFrame['tip'] / tipsDataFrame['total_bill']

In [19]:
tipsDataFrame.head(5)

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name         CC Number Payment ID  tips_percentage  
0  Christy Cunningham  3560325168603410    Sun2959         5.944673  
1      Douglas Tucker  4478071379779230    Sun4608        16.054159  
2      Travis Walters  6011812112971322    Sun4458        16.658734  
3    Nathaniel Harris  4676137647685994    Sun5260        13.978041  
4        Tonya Carter  4832732618637221    Sun2251        14.680765

Adjusting existing column - round decimal place

In [20]:
#tipsDataFrame['tips_percentage'] = np.round(tipsDataFrame['tips_percentage'])
np.round(tipsDataFrame['tips_percentage'], 0)

0       6.0
1      16.0
2      17.0
3      14.0
4      15.0
       ... 
239    20.0
240     7.0
241     9.0
242    10.0
243    16.0
Name: tips_percentage, Length: 244, dtype: float64

In [21]:
tipsDataFrame['tips_percentage'].convert_dtypes(convert_integer=True)

0       5.944673
1      16.054159
2      16.658734
3      13.978041
4      14.680765
         ...    
239    20.392697
240     7.358352
241     8.822232
242     9.820426
243    15.974441
Name: tips_percentage, Length: 244, dtype: Float64

In [22]:
tipsDataFrame.head(5)

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name         CC Number Payment ID  tips_percentage  
0  Christy Cunningham  3560325168603410    Sun2959         5.944673  
1      Douglas Tucker  4478071379779230    Sun4608        16.054159  
2      Travis Walters  6011812112971322    Sun4458        16.658734  
3    Nathaniel Harris  4676137647685994    Sun5260        13.978041  
4        Tonya Carter  4832732618637221    Sun2251        14.680765

Create Index

In [23]:
tipsDataFrame = tipsDataFrame.set_index('Payment ID')

In [24]:
tipsDataFrame

total_bill   tip     sex smoker   day    time  size  \
Payment ID                                                        
Sun2959          16.99  1.01  Female     No   Sun  Dinner     2   
Sun4608          10.34  1.66    Male     No   Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No   Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No   Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No   Sun  Dinner     4   
...                ...   ...     ...    ...   ...     ...   ...   
Sat2657          29.03  5.92    Male     No   Sat  Dinner     3   
Sat1766          27.18  2.00  Female    Yes   Sat  Dinner     2   
Sat3880          22.67  2.00    Male    Yes   Sat  Dinner     2   
Sat17            17.82  1.75    Male     No   Sat  Dinner     2   
Thur672          18.78  3.00  Female     No  Thur  Dinner     2   

            price_per_person          Payer Name         CC Number  \
Payment ID                                                           
Sun2959                 8.49  Christy Cunningham  3560325168603410   
Sun4608                 3.45      Douglas Tucker  4478071379779230   
Sun4458                 7.00      Travis Walters  6011812112971322   
Sun5260                11.84    Nathaniel Harris  4676137647685994   
Sun2251                 6.15        Tonya Carter  4832732618637221   
...                      ...                 ...               ...   
Sat2657                 9.68       Michael Avila  5296068606052842   
Sat1766                13.59      Monica Sanders  3506806155565404   
Sat3880                11.34          Keith Wong  6011891618747196   
Sat17                   8.91        Dennis Dixon     4375220550950   
Thur672                 9.39     Michelle Hardin  3511451626698139   

            tips_percentage  
Payment ID                   
Sun2959            5.944673  
Sun4608           16.054159  
Sun4458           16.658734  
Sun5260           13.978041  
Sun2251           14.680765  
...                     ...  
Sat2657           20.392697  
Sat1766            7.358352  
Sat3880            8.822232  
Sat17              9.820426  
Thur672           15.974441  

[244 rows x 11 columns]

In [25]:
tipsDataFrame.info()

<class 'pandas.core.frame.DataFrame'>
Index: 244 entries, Sun2959 to Thur672
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object 
 3   smoker            244 non-null    object 
 4   day               244 non-null    object 
 5   time              244 non-null    object 
 6   size              244 non-null    int64  
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object 
 9   CC Number         244 non-null    int64  
 10  tips_percentage   244 non-null    float64
dtypes: float64(4), int64(2), object(5)
memory usage: 22.9+ KB


In [26]:
tipsDataFrame.loc['Sun3775']

total_bill                     14.78
tip                             3.23
sex                             Male
smoker                            No
day                              Sun
time                          Dinner
size                               2
price_per_person                7.39
Payer Name             Jerome Abbott
CC Number           3532124519049786
tips_percentage            21.853857
Name: Sun3775, dtype: object

In [27]:
tipsDataFrame.loc[['Sun3775', 'Sun4608']]

total_bill   tip   sex smoker  day    time  size  \
Payment ID                                                     
Sun3775          14.78  3.23  Male     No  Sun  Dinner     2   
Sun4608          10.34  1.66  Male     No  Sun  Dinner     3   

            price_per_person      Payer Name         CC Number  \
Payment ID                                                       
Sun3775                 7.39   Jerome Abbott  3532124519049786   
Sun4608                 3.45  Douglas Tucker  4478071379779230   

            tips_percentage  
Payment ID                   
Sun3775           21.853857  
Sun4608           16.054159