In [2]:
import numpy as np
import pandas as pd

In [2]:
mylist = [1,2,3]

In [3]:
print(mylist)

[1, 2, 3]


In [5]:
type(mylist)

list

In [4]:
myarr = np.array(mylist)

In [13]:
myarr

array([1, 2, 3])

In [15]:
type(myarr)

numpy.ndarray

In [5]:
my_matrix = [[1,2,3], [4,5,6], [7,8,8]]

In [6]:
my_np_matrix = np.array(my_matrix)

In [9]:
print(my_np_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 8]]


In [11]:
zero_array = np.zeros(5)
print(zero_array)

[0. 0. 0. 0. 0.]


In [3]:
twoD_zero_array = np.zeros((5,5))
print(twoD_zero_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
print(np.ones((5,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
np.linspace(0,12,4)

array([ 0.,  4.,  8., 12.])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
print(np.linspace(0,10,101))

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7
  9.8  9.9 10. ]
