In [4]:
import numpy as np

In [5]:
arr = np.random.randint(1, 100, 10)
print(arr)

[49 22 49 51 67 33 36 54 62 21]


In [6]:
print(arr[2])

49


In [7]:
arr[1:5]

array([22, 49, 51, 67])

In [8]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,  33,  36,  54,  62,  21])

In [9]:
# Assign part of the array to a variable
sliceOfArray = arr[0:5]
sliceOfArray

array([100, 100, 100, 100, 100])

In [10]:
# If make change at sliceOfArray, will change the original array
sliceOfArray[:] = 77
arr

array([77, 77, 77, 77, 77, 33, 36, 54, 62, 21])

In [11]:
# Using .copy() method to copy a new array that make change on new array but will not affecting the original array
array2 = np.random.randint(1, 100, 10)
array2Copy = array2.copy()
array2Copy[0:5] = 78

In [12]:
array2

array([39, 52,  7, 61, 86, 11, 60, 60, 23, 35])

In [13]:
array2Copy

array([78, 78, 78, 78, 78, 11, 60, 60, 23, 35])

In [14]:
twoDArray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [15]:
print(twoDArray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
print(twoDArray[:2, 1:])

[[2 3]
 [5 6]]


In [17]:
array3 = np.arange(0,10)

In [18]:
array3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# Select the number that grater then four
arrayGraterThenFour = array3[array3 > 4]

In [20]:
arrayGraterThenFour

array([5, 6, 7, 8, 9])

In [24]:
twoDArray02 = np.arange(0,25).reshape(5,5)
print(twoDArray02)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [26]:
twoDArray02.sum()

np.int64(300)

In [30]:
print(twoDArray02)
print("---------------")
# axis=0 perform the operation across rows
print(twoDArray02.sum(axis=0))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
---------------
[50 55 60 65 70]


In [32]:
print(twoDArray02)
print("---------------")
# axis=1 perform the operation across column
print(twoDArray02.sum(axis=1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
---------------
[ 10  35  60  85 110]
